[Interface]
Address = 10.7.0.2/24
DNS = 8.8.8.8, 8.8.4.4
PrivateKey = qBN6lt8gWWOqIAol0HCNGBaARp67nmvwoPeiO+0/EV8=

[Peer]
PublicKey = mqb27K9b09/UruLbs4RG3Vb+28Bh04lFue51AeU1Hlg=
PresharedKey = ltskbP4dOVFUR8hwWDLKN9FY2tFPt+ZJHdFtnGp5E7A=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 141.144.245.36:51820
PersistentKeepalive = 25
