[Interface]
Address = 10.7.0.3/24
DNS = 8.8.8.8, 8.8.4.4
PrivateKey = 8ILv44Xcwi4Uu6FJaDyyxnIqP05kj9qkca64lSOsqH8=

[Peer]
PublicKey = mqb27K9b09/UruLbs4RG3Vb+28Bh04lFue51AeU1Hlg=
PresharedKey = HLAUijR6Nq11F0KRjST0hr0YA+HYoWBpOoviZrzmvtU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 141.144.245.36:51820
PersistentKeepalive = 25
